version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: eren12416
      MYSQL_DATABASE: egzersiz_uygulamasi
    ports:
      - "3307:3306"
    networks:
      - my_network

  server:
    build: .
    container_name: node_server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: eren12416
      DB_NAME: egzersiz_uygulamasi
    networks:
      - my_network
    command: ["npm", "start"]

networks:
  my_network:
    driver: bridge
